### ISSUE TITLE
🛑 Explorer is down

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/uptime#26]
In [`32b6c74`](https://github.com/cowprotocol/uptime/commit/32b6c745eb519825ca05a012f1cfda2c69f3e33c
), Explorer (http://explorer.cow.fi) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by MartinquaXD** [comment]
The site is functional again.

**Comment by MartinquaXD** [comment]
The page looked functional because I manually trusted it at some point.
The issue is an expired SSL certificate and still ongoing.
